spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    #运行的环境
    active: test
  application:
    name: chatroom
  datasource:
    url: jdbc:mysql://${chatroom.mysql.ip}:${chatroom.mysql.port}/${chatroom.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${chatroom.mysql.username}
    password: ${chatroom.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis服务器地址
    host: ${chatroom.redis.host}
    # Redis服务器端口号
    port: ${chatroom.redis.port}
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: ${chatroom.redis.password}
  jackson:
    serialization:
      write-dates-as-timestamps: true
wx:
  mp:
    #    callback: http://f4cd-113-92-129-127.ngrok.io
    callback: ${chatroom.wx.callback}
    configs:
      - appId: ${chatroom.wx.appId} # 第一个公众号的appid
        secret: ${chatroom.wx.secret} # 公众号的appsecret
        token: ${chatroom.wx.token} # 接口配置里的Token值
        aesKey: ${chatroom.wx.aesKey} # 接口配置里的EncodingAESKey值


jwt:
  secret: ${chatroom.jwt.secret}